- hosts: localhost
  vars_files:
   - files_list.yml
  tasks:
   - name: check file checksum
     stat:
         path: "{{ item.name }}"
     with_items:
      - "{{ files }}"
     register: data

   - debug:
        msg: "Checksum Passed {{ item.stat.path}}"
     when: item.item.checksum == item.stat.checksum + ' ' + item.stat.path
     loop: "{{ data.results }}"

   - debug:
        msg: "Checksum Failed {{ item.stat.path}}"
     when: item.item.checksum != item.stat.checksum + ' ' + item.stat.path
     loop: "{{ data.results }}"
